### PR TITLE
Upgrade cypress to v12.6.0

### PR DESCRIPTION
**Pull request by samanthaandrews**
@kristojorg can you see if this at least opens Cypress for you? I'm getting webpack polyfill errors, but Cypress tests do open for me and I fixed the config stuff.

I removed the login code from tests and was planning on updating these tests to add the fake cookie instead, while filling in the missing server calls and fixtures in MSW.

But part of me wants to just implement Playwright instead 😬

### CODE REVIEW

**Comment by Toxiapo** [comment]
I can get the cypress to start on my m1 Mac; however, I had to change quite a bit of settings, and I got the webpack compilation errors when running the specs. Looks like we need to define webpack configs for Cypress.
```
Module not found: Error: Can't resolve 'http' in '.../node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

If this continues causing issues for everyone, I am also open to the playwright migration

**Comment by samanthaandrews** [comment]
I have a branch started with Playwright running, but it's not quite playing nicely with typescript yet. The setup was strangely much easier in the OEH project using Vite. I'm going to spend more time tinkering on it today.

**Comment by kristojorg** [comment]
BTW I am going to rebase this on main so we can merge it in separately and then I can pull main in to my PR

**Comment by samanthaandrews** [comment]
Closing this for now. I linked this PR to @kristojorg 's doc that includes more details: https://docs.google.com/document/d/1wJnpp7zHWwc1Y4n1xVVSDZjS0H9ROtMrldlJagmmNzc/edit

**Pull request closed without merging**
