### PR TITLE
Updates web-reader version in OEW

### PR DESCRIPTION
**Pull request by oliviawongnyc**
- Updates version of web-reader in OEW from ^3.2.5 to ^4.1.0 to include updates to the settings panel.

### CODE REVIEW

**Review by kristojorg — APPROVED** [review]
LGTM!

**Review by Toxiapo — APPROVED** [review]
🎉

**Comment by samanthaandrews** [comment]
I _think_ we can close this since we updated the web-reader in a different PR. Is that right @Toxiapo ?

**Comment by Toxiapo** [comment]
Yes! @samanthaandrews

Closing this as https://github.com/NYPL/ereading-clients/pull/597 already upgraded the package.

**Pull request closed without merging**
