### PR TITLE
OE-846: Support iOS 13+ browsers

### PR DESCRIPTION
**Pull request by kristojorg**
This PR adds `@vitejs/plugin-legacy` to transpile our JS down to versions compatible with iOS 13+.

### CODE REVIEW

**Review by ettore — COMMENTED** [review]
that's a ton of changes in package.json, if that looks ok to you guys it's ok for me as well. At least there are minimal code changes.

If we want to include this in the demo though, as best practice this PR should target the release branch instead of `main`: otherwise we'll need to merge `main` onto the release branch and that might bring in other changes we do not want.

**Comment by samanthaandrews** [comment]
@kristojorg were you able to test this on a simulator running iOS v12 or 13? Just trying to figure out our confidence levels with this.

**Comment by kristojorg** [comment]
I tested actually only on iOS 14 so far. Takes a while to download extra runtimes but I got 12 and 13 downloading now : )

**Comment by kristojorg** [comment]
Good point @ettore, I've rebased on the release branch and changed the base

**Comment by ettore** [comment]
I verified this functions correctly on iOS 13.7 simulator.

**Comment by kristojorg** [comment]
If you approve, feel free to merge @samanthaandrews

**Review by ettore — APPROVED** [review]

**Review by samanthaandrews — APPROVED** [review]

**Pull request merged**
